### PR TITLE
use Travis-CI's D support

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by etcimon** [comment]
Yeah.. I tried that, took me about 1 hour to resolve myself to using my libasync travis file.

**Comment by MartinNowak** [comment]
Somehow it picks up ruby as language, no idea why that happens.
https://travis-ci.org/etcimon/memutils/builds/49345764#L4
Looks like a caching problem, try to toggle the travis-ci on/off switch for this repo, then I'll retrigger the pull test.

**Comment by etcimon** [comment]
> Looks like a caching problem, try to toggle the travis-ci on/off switch for this repo, then I'll retrigger the pull test.

I've tried that before though, only thing I didn't try is deleting the repo in github.

**Comment by MartinNowak** [comment]
> I've tried that before though, only thing I didn't try is deleting the repo in github.

It's apparently some global problem, currently "debugging".
https://travis-ci.org/MartinNowak/qcheck/builds/49351669

**Comment by etcimon** [comment]
Maybe there's a travis environment variable I can try?

**Comment by MartinNowak** [comment]
> Maybe there's a travis environment variable I can try?

Temporary outage apparently, would be interesting to know on which side.
https://travis-ci.org/MartinNowak/qcheck/builds/49352725
I retriggered the build, hopefully works now.

**Comment by etcimon** [comment]
For me it shows that your's is passing

**Comment by MartinNowak** [comment]
> Maybe there's a travis environment variable I can try?

But it still detects your repo incorrectly. Have you set any env variables on the project? There is a settings switch on the upper right.

**Comment by etcimon** [comment]
> But it still detects your repo incorrectly. Have you set any env variables on the project?

Nope, everything is default. Maybe it looks at the initial commit where there's no D code?

**Comment by etcimon** [comment]
Looks like the initial commit has to have D code inside it >:(

Now it works yay!

**Comment by MartinNowak** [comment]
Found the issue, you had a UTF-8 BOM mark in your .travis.yml.

```
➜ memutils git:(travis-ci) hexdump -C .travis.yml 
00000000  ef bb bf 6c 61 6e 67 75  61 67 65 3a 20 64 0a 73  |...language: d.s|
00000010  75 64 6f 3a 20 66 61 6c  73 65 0a                 |udo: false.|
0000001b
```

https://travis-ci.org/MartinNowak/memutils/builds/49357204

**Comment by etcimon** [comment]
Of course, I created the first one with notepad++, and the newer one with vim. Not sure why BOM would cause issues, but still good to know !

**Comment by MartinNowak** [comment]
Filed as [Travis-CI fails to parse .travis.yml with UTF BOM mark · Issue #3172 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/3172).

**Pull request closed without merging**
