### PR TITLE
Fix compilation on 2.069.0-rc.1

### PR DESCRIPTION
**Pull request by s-ludwig**

### CODE REVIEW

**Comment by etcimon** [comment]
I'm going to force an update on the existing release version because it's a pain to create a new one for each library just for this

**Comment by s-ludwig** [comment]
Don't the other libraries all specify `~>0.4.0`?

**Comment by etcimon** [comment]
I think only botan was updated actually, I'll just tag a new release then

**Comment by s-ludwig** [comment]
OK, I'll then update vibe.d and tag an RC version.

**Comment by etcimon** [comment]
ACtually, give me a few minutes to fix the libasync filestream problem first

**Comment by s-ludwig** [comment]
OK

**Comment by etcimon** [comment]
ok done: https://github.com/rejectedsoftware/vibe.d/pull/1227

**Pull request merged**
